FROM nginxinc/nginx-unprivileged:1.27-alpine

ARG PUBLIC_URL=/
ENV PUBLIC_URL=${PUBLIC_URL}

USER root

RUN rm -f /etc/nginx/conf.d/default.conf

COPY .docker/Viewer-v3.x /usr/src

COPY platform/app/dist /usr/share/nginx/html

COPY platform/app/dist/dicom-microscopy-viewer \
    /usr/share/nginx/html/dicom-microscopy-viewer

RUN chown -R nginx:nginx /usr/share/nginx/html \
    && chmod -R 777 /usr/share/nginx/html \
    && chmod 777 /usr/src/entrypoint.sh

USER nginx

ENTRYPOINT ["/usr/src/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
